# http://dx.doi.org/10.7265/N5K072F8
seaice.nc:
# only get the sea ice
	wget -c -nd -r ftp://sidads.colorado.edu/DATASETS/NOAA/G02135/north/monthly/data/
	wget -c -nd -r ftp://sidads.colorado.edu/DATASETS/NOAA/G02135/south/monthly/data/
	wget -c -nd -r ftp://sidads.colorado.edu/DATASETS/NOAA/G02135/seaice_analysis/
