all: imbie_dataset-2018_07_23.xlsx imbie_dataset_greenland_dynamics-2019_12_10.xlsx imbie_dataset_greenland_dynamics-2020_02_28.xlsx
imbie_dataset_greenland_dynamics-2019_12_10.xlsx:
	wget -c http://imbie.org/wp-content/uploads/2012/11/imbie_dataset_greenland_dynamics-2019_12_10.xlsx
imbie_dataset-2018_07_23.xlsx:
	wget -c http://imbie.org/data-files/imbie_dataset-2018_07_23.xlsx
imbie_dataset_greenland_dynamics-2020_02_28.xlsx:
	wget -c http://imbie.org/wp-content/uploads/2012/11/imbie_dataset_greenland_dynamics-2020_02_28.xlsx
