all: uwnd.10m.mon.mean.nc vwnd.10m.mon.mean.nc

uwnd.10m.mon.mean.nc:
	wget -c https://www.esrl.noaa.gov/psd/thredds/fileServer/Datasets/ncep.reanalysis.derived/surface_gauss/uwnd.10m.mon.mean.nc
vwnd.10m.mon.mean.nc:
	wget -c https://www.esrl.noaa.gov/psd/thredds/fileServer/Datasets/ncep.reanalysis.derived/surface_gauss/vwnd.10m.mon.mean.nc
