#!/usr/bin/env python
import pathlib

import pandas


ocean_surface = 3.619e+14       # m2
for name in ['ocean_mass', 'greenland_mass', 'antarctica_mass']:
    path = next(pathlib.Path('.').glob(name + '*.txt'))
    df = pandas.read_csv(
        path,
        comment='H',                # HDR
        names=('year', 'mass', 'std'),
        sep='\s+'
    )

    # gigatonne, assuming metric to kg, * 1l/kg * m3/l
    df['volume'] = df['mass'] * 1e12 * 1.0 * 1e-3
    df['slr'] = -df['volume'] / ocean_surface

    df.to_json(name + '.json', orient='records')
